//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.22 at 11:17:07 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/AnaMijailovic/XML-Tim19/cover_letter", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ftn.scientific_papers.model.cover_letter;
