PREFIX xml: <https://github.com/AnaMijailovic/XML-Tim19/> 
PREFIX pred: <https://github.com/AnaMijailovic/XML-Tim19/predicate/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?paper
FROM <http://localhost:8080/fuseki/PapersDataset/data/scientificPapers>
WHERE {
 ?paper pred:quotes ?quotedPaper .
 FILTER( str(?quotedPaper) = "{{quotedPaper}}" ) .
}